repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix, empulse, tests ]
      # Run the formatter.
      - id: ruff-format
        args: [ empulse, tests ]