name: documentation

on: [push, pull_request]

jobs:

  build-docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry
          poetry install

      - name: "Build documentation"
        run: poetry run sphinx-build docs static

      # we need nojekyll or github will ignore folders starting with "_"
      - name: "Copy static files"
        run: |

          mv .nojekyll static


      - name: "Deploy Docs 🚀"
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: static # The folder the action should deploy.