name: Tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    tags-ignore: ["**"]
  pull_request:

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        env:
          - "3.13-tests"
          - "3.12-tests"
          - "3.11-tests"
          - "3.10-tests"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: Extract Python version
        id: extract-version
        run: echo "VERSION=${{ matrix.env }}" | sed 's/-tests//' | tee -a $GITHUB_ENV
      - name: Install tox
        run: uv tool install --python-preference only-managed --python 3.13 tox --with .
      - name: Install Python
        if: env.VERSION != '3.13'
        run: uv python install --python-preference only-managed ${{ env.VERSION }}
      - name: Setup test suite
        run: tox run -vv --notest --skip-missing-interpreters false -e py${{ matrix.env }}
        env:
          UV_PYTHON_PREFERENCE: "only-managed"
      - name: Run test suite
        run: tox run --skip-pkg-install -e py${{ matrix.env }}
        env:
          PYTEST_ADDOPTS: "-vv --durations=20"
          DIFF_AGAINST: HEAD
          UV_PYTHON_PREFERENCE: "only-managed"